# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Chinese', models.FloatField(default=0, max_length=5)),
                ('Math', models.FloatField(default=0, max_length=5)),
                ('English', models.FloatField(default=0, max_length=5)),
                ('Physics', models.FloatField(default=0, max_length=5)),
                ('Chemistry', models.FloatField(default=0, max_length=5)),
                ('password', models.CharField(max_length=20)),
                ('sum', models.FloatField(default=0, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeacherID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
