# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Password',
            new_name='password',
        ),
    ]
